"""Таблицы для результатов ирбиса

Revision ID: 012b838d0f0e
Revises: eb60dad69d75
Create Date: 2025-07-24 15:05:21.800913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012b838d0f0e'
down_revision: Union[str, None] = 'eb60dad69d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons_uuid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('person_uuid', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['user_queries.query_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arbitr_court_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('court_name_val', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=1), nullable=False),
    sa.Column('case_date', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('case_type', sa.String(length=1), nullable=False),
    sa.Column('response_id', sa.String(length=64), nullable=False),
    sa.Column('address_val', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arbitr_court_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.Column('plaintiff', sa.Integer(), nullable=False),
    sa.Column('responder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bankruptcy_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('second_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.String(length=64), nullable=False),
    sa.Column('born_place', sa.String(length=256), nullable=False),
    sa.Column('inn', sa.String(length=64), nullable=False),
    sa.Column('ogrn', sa.String(length=64), nullable=False),
    sa.Column('snils', sa.String(length=64), nullable=False),
    sa.Column('old_name', sa.String(length=64), nullable=True),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('region_name', sa.String(length=64), nullable=False),
    sa.Column('information', sa.String(length=256), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bankruptcy_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corruption_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('organization', sa.String(length=256), nullable=False),
    sa.Column('position', sa.String(length=256), nullable=False),
    sa.Column('normative_act', sa.String(length=256), nullable=False),
    sa.Column('application_date', sa.String(length=64), nullable=False),
    sa.Column('publish_date', sa.String(length=64), nullable=False),
    sa.Column('excluded_reason', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corruption_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_general_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_general_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_general_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('search_type', sa.String(length=64), nullable=False),
    sa.Column('court_type', sa.String(length=1), nullable=False),
    sa.Column('plan', sa.Integer(), nullable=True),
    sa.Column('deff', sa.Integer(), nullable=True),
    sa.Column('declarant', sa.Integer(), nullable=True),
    sa.Column('face', sa.Integer(), nullable=True),
    sa.Column('lawyer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposits_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('pledge_count', sa.Integer(), nullable=False),
    sa.Column('pledge_type', sa.String(length=64), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposits_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('pledge_count', sa.Integer(), nullable=False),
    sa.Column('pledge_type', sa.String(length=64), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disqualified_person_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('reestr_key', sa.String(length=128), nullable=False),
    sa.Column('birth_date', sa.String(length=64), nullable=False),
    sa.Column('fio', sa.String(length=128), nullable=False),
    sa.Column('article', sa.String(length=128), nullable=False),
    sa.Column('start_date_disq', sa.String(length=64), nullable=False),
    sa.Column('end_date_disq', sa.String(length=64), nullable=False),
    sa.Column('bornplace', sa.String(length=128), nullable=False),
    sa.Column('fio_judge', sa.String(length=128), nullable=False),
    sa.Column('office_judge', sa.String(length=128), nullable=False),
    sa.Column('legal_name', sa.String(length=128), nullable=False),
    sa.Column('office', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disqualified_person_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fssp_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=128), nullable=False),
    sa.Column('fio', sa.String(length=128), nullable=False),
    sa.Column('rosp', sa.String(length=128), nullable=False),
    sa.Column('type_ip', sa.String(length=128), nullable=False),
    sa.Column('summ', sa.Numeric(), nullable=False),
    sa.Column('rekv', sa.String(length=128), nullable=False),
    sa.Column('end_cause', sa.String(length=64), nullable=False),
    sa.Column('pristav', sa.String(length=128), nullable=False),
    sa.Column('pristav_phones', sa.String(length=128), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fssp_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('type_sum', sa.Numeric(), nullable=False),
    sa.Column('type_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_index_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('scoring', sa.Numeric(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('progress', sa.Numeric(), nullable=False),
    sa.Column('popularity_full', sa.Numeric(), nullable=False),
    sa.Column('popularity_short', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_in_org_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Numeric(), nullable=False),
    sa.Column('part_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_in_org_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Numeric(), nullable=False),
    sa.Column('part_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_arrears_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('money_name', sa.String(length=8), nullable=False),
    sa.Column('money_code', sa.Integer(), nullable=False),
    sa.Column('money_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terror_list_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_uuid', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.String(length=128), nullable=False),
    sa.Column('fio', sa.String(length=128), nullable=False),
    sa.Column('birth_date', sa.String(length=64), nullable=False),
    sa.Column('birth_place', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['person_uuid'], ['persons_uuid.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_general_faces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('face', sa.String(), nullable=False),
    sa.Column('papers', sa.String(), nullable=True),
    sa.Column('papers_pretty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_general_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_general_header',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('court_name', sa.String(), nullable=False),
    sa.Column('process_type', sa.String(length=1), nullable=False),
    sa.Column('start_date', sa.String(length=64), nullable=False),
    sa.Column('end_date', sa.String(length=64), nullable=False),
    sa.Column('review', sa.Integer(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('articles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('papers', sa.String(), nullable=True),
    sa.Column('papers_pretty', sa.String(), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_general_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_general_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('progress_date', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_general_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposits_parties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('subtype', sa.String(length=16), nullable=False),
    sa.Column('birth_date', sa.String(length=64), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposits_pledges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('pledge_id_name', sa.String(length=64), nullable=False),
    sa.Column('pledge_id', sa.String(length=128), nullable=False),
    sa.Column('pledge_type', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_in_org_individual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part_in_org_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_in_org_org',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('adress', sa.String(length=200), nullable=False),
    sa.Column('okved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part_in_org_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_arrears_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arrear_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('field_id', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=256), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['arrear_id'], ['tax_arrears_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_in_org_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['individual_id'], ['part_in_org_individual.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_in_org_roles')
    op.drop_table('tax_arrears_fields')
    op.drop_table('part_in_org_org')
    op.drop_table('part_in_org_individual')
    op.drop_table('deposits_pledges')
    op.drop_table('deposits_parties')
    op.drop_table('court_general_progress')
    op.drop_table('court_general_header')
    op.drop_table('court_general_faces')
    op.drop_table('terror_list_full')
    op.drop_table('tax_arrears_full')
    op.drop_table('part_in_org_preview')
    op.drop_table('part_in_org_full')
    op.drop_table('ml_index_full')
    op.drop_table('fssp_preview')
    op.drop_table('fssp_full')
    op.drop_table('disqualified_person_preview')
    op.drop_table('disqualified_person_full')
    op.drop_table('deposits_preview')
    op.drop_table('deposits_full')
    op.drop_table('court_general_preview')
    op.drop_table('court_general_full')
    op.drop_table('court_general_category')
    op.drop_table('corruption_preview')
    op.drop_table('corruption_full')
    op.drop_table('bankruptcy_preview')
    op.drop_table('bankruptcy_full')
    op.drop_table('arbitr_court_preview')
    op.drop_table('arbitr_court_full')
    op.drop_table('persons_uuid')
    # ### end Alembic commands ###
