"""добавлено поле для хранение типа поиска

Revision ID: 02c8382f08c7
Revises: 27a4c51126a6
Create Date: 2025-09-01 19:28:49.563193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c8382f08c7'
down_revision: Union[str, None] = '27a4c51126a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitr_court_full', sa.Column('search_type', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arbitr_court_full', 'search_type')
    # ### end Alembic commands ###
