"""поправлены ирбис модели

Revision ID: 06e50cccaa96
Revises: 4e63f2bbd51a
Create Date: 2025-08-25 12:24:37.850692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e50cccaa96'
down_revision: Union[str, None] = '4e63f2bbd51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_general_progress', sa.Column('name', sa.String(), nullable=True))
    op.add_column('court_general_progress', sa.Column('resolution', sa.String(), nullable=True))
    op.drop_column('court_general_progress', 'note')
    op.drop_column('court_general_progress', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_general_progress', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('court_general_progress', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('court_general_progress', 'resolution')
    op.drop_column('court_general_progress', 'name')
    # ### end Alembic commands ###
