"""поправлена таблица залогов

Revision ID: 1014f0ecd02c
Revises: c6779c487337
Create Date: 2025-09-03 14:38:18.461558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1014f0ecd02c'
down_revision: Union[str, None] = 'c6779c487337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pledges_full',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('irbis_person_id', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.String(length=40), nullable=True),
    sa.Column('pledge_reestr_number', sa.String(length=20), nullable=True),
    sa.Column('pledge_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['irbis_person_id'], ['irbis_person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pledges_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('irbis_person_id', sa.Integer(), nullable=False),
    sa.Column('pledge_count', sa.Integer(), nullable=False),
    sa.Column('pledge_type', sa.String(length=128), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['irbis_person_id'], ['irbis_person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pledge_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pledge_id', sa.Integer(), nullable=False),
    sa.Column('pledge_num_name', sa.String(length=128), nullable=False),
    sa.Column('pledge_num', sa.String(length=512), nullable=False),
    sa.Column('pledge_type', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['pledge_id'], ['pledges_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pledge_parties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pledge_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('subtype', sa.String(length=16), nullable=False),
    sa.Column('birth_date', sa.String(length=128), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['pledge_id'], ['pledges_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deposits_pledges')
    op.drop_table('deposits_parties')
    op.drop_table('deposits_preview')
    op.drop_table('deposits_full')
    op.drop_column('terror_list_full', 'response_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terror_list_full', sa.Column('response_id', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_table('deposits_full',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('deposits_full_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pledge_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pledge_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('irbis_person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['irbis_person_id'], ['irbis_person.id'], name='deposits_full_irbis_person_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deposits_full_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('deposits_preview',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pledge_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pledge_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('irbis_person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['irbis_person_id'], ['irbis_person.id'], name='deposits_preview_irbis_person_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deposits_preview_pkey')
    )
    op.create_table('deposits_parties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deposit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('subtype', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('inn', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ogrn', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits_full.id'], name='deposits_parties_deposit_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deposits_parties_pkey')
    )
    op.create_table('deposits_pledges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deposit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pledge_id_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('pledge_id', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('pledge_type', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits_full.id'], name='deposits_pledges_deposit_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deposits_pledges_pkey')
    )
    op.drop_table('pledge_parties')
    op.drop_table('pledge_items')
    op.drop_table('pledges_preview')
    op.drop_table('pledges_full')
    # ### end Alembic commands ###
