"""обновлена таблица с хранением данных запроса

Revision ID: 13775baad10d
Revises: d77929471593
Create Date: 2025-08-04 14:55:41.089354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13775baad10d'
down_revision: Union[str, None] = 'd77929471593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('queries_data', sa.Column('info', sa.Text(), nullable=True))
    op.add_column('queries_data', sa.Column('link', sa.Text(), nullable=True))
    op.add_column('queries_data', sa.Column('publication_date', sa.Text(), nullable=True))
    op.drop_column('queries_data', 'found_links')
    op.drop_column('queries_data', 'found_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('found_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('queries_data', sa.Column('found_links', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('queries_data', 'publication_date')
    op.drop_column('queries_data', 'link')
    op.drop_column('queries_data', 'info')
    op.drop_column('queries_data', 'title')
    # ### end Alembic commands ###
