"""добавлена таблица user_balance_history

Revision ID: 1f787521bd40
Revises: 7334917926df
Create Date: 2026-03-28 21:19:53.570015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f787521bd40'
down_revision: Union[str, None] = '7334917926df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_balance_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Double(precision=53), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['user_queries.query_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_balance_history_user_id'), 'user_balance_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_balance_history_user_id'), table_name='user_balance_history')
    op.drop_table('user_balance_history')
    # ### end Alembic commands ###
