"""добавлена табличка с регионами. Добавлена доп информация в запросе irbis

Revision ID: 220947b8973f
Revises: ce13f5a7e7ba
Create Date: 2025-08-26 11:03:11.157067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220947b8973f'
down_revision: Union[str, None] = 'ce13f5a7e7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('subject_number')
    )
    op.create_table('person_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['irbis_person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['region_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('irbis_person', sa.Column('fullname', sa.String(length=128), nullable=False))
    op.add_column('irbis_person', sa.Column('birth_date', sa.String(length=20), nullable=True))
    op.add_column('irbis_person', sa.Column('passport_series', sa.String(length=4), nullable=True))
    op.add_column('irbis_person', sa.Column('passport_number', sa.String(length=6), nullable=True))
    op.add_column('irbis_person', sa.Column('inn', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irbis_person', 'inn')
    op.drop_column('irbis_person', 'passport_number')
    op.drop_column('irbis_person', 'passport_series')
    op.drop_column('irbis_person', 'birth_date')
    op.drop_column('irbis_person', 'fullname')
    op.drop_table('person_regions')
    op.drop_table('region_subjects')
    # ### end Alembic commands ###
