"""добавлены связи для арбитражных дел

Revision ID: 27a4c51126a6
Revises: 348a1d03a2ae
Create Date: 2025-09-01 19:23:15.870154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a4c51126a6'
down_revision: Union[str, None] = '348a1d03a2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitr_court_oponents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arbitration_court_full_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['arbitration_court_full_id'], ['arbitr_court_full.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('arbitr_court_full', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('arbitr_court_full', sa.Column('case_number', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'arbitr_court_full', 'region_subjects', ['region_id'], ['id'], ondelete='CASCADE')
    op.drop_column('arbitr_court_full', 'response_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitr_court_full', sa.Column('response_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'arbitr_court_full', type_='foreignkey')
    op.drop_column('arbitr_court_full', 'case_number')
    op.drop_column('arbitr_court_full', 'region_id')
    op.drop_table('arbitr_court_oponents')
    # ### end Alembic commands ###
