"""добавлена связь процесса с записью

Revision ID: 348a1d03a2ae
Revises: 97172baf9769
Create Date: 2025-08-27 20:22:02.132431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348a1d03a2ae'
down_revision: Union[str, None] = '97172baf9769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_general_full', sa.Column('process_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'court_general_full', 'process_types', ['process_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('court_general_full', 'process_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_general_full', sa.Column('process_type', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'court_general_full', type_='foreignkey')
    op.drop_column('court_general_full', 'process_type_id')
    # ### end Alembic commands ###
