"""добавлена таблица для хранения слов запроса

Revision ID: 3a63e06ad400
Revises: a0f7b833fef7
Create Date: 2025-08-10 12:29:17.767585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a63e06ad400'
down_revision: Union[str, None] = 'a0f7b833fef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_query_word_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_word_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_query_word',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('query_word', sa.String(length=75), nullable=True),
    sa.Column('query_word_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['user_queries.query_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_word_type_id'], ['additional_query_word_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('keywords', 'keyword_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keywords', 'keyword_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('additional_query_word')
    op.drop_table('additional_query_word_type')
    # ### end Alembic commands ###
