"""добавлено новое поле в таблицу запросов

Revision ID: 3da7d5f9b623
Revises: 13775baad10d
Create Date: 2025-08-06 10:24:33.689230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da7d5f9b623'
down_revision: Union[str, None] = '13775baad10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('keyword_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries_data', 'keyword_type')
    # ### end Alembic commands ###
