"""поправлены ирбис модели

Revision ID: 4e63f2bbd51a
Revises: e1c8f66cf49a
Create Date: 2025-08-25 11:51:14.405583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e63f2bbd51a'
down_revision: Union[str, None] = 'e1c8f66cf49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irbis_person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('person_uuid', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['user_queries.query_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('court_general_header')
    op.add_column('arbitr_court_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'arbitr_court_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('arbitr_court_full', 'person_uuid')
    op.add_column('arbitr_court_preview', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'arbitr_court_preview', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('arbitr_court_preview', 'person_uuid')
    op.add_column('bankruptcy_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bankruptcy_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bankruptcy_full', 'person_uuid')
    op.add_column('bankruptcy_preview', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bankruptcy_preview', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bankruptcy_preview', 'person_uuid')
    op.add_column('corruption_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'corruption_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('corruption_full', 'person_uuid')
    op.add_column('corruption_preview', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'corruption_preview', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('corruption_preview', 'person_uuid')
    op.add_column('court_general_category', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'court_general_category', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('court_general_category', 'person_uuid')
    op.add_column('court_general_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.add_column('court_general_full', sa.Column('case_number', sa.String(), nullable=False))
    op.add_column('court_general_full', sa.Column('region', sa.Integer(), nullable=False))
    op.add_column('court_general_full', sa.Column('court_name', sa.String(), nullable=False))
    op.add_column('court_general_full', sa.Column('process_type', sa.String(length=1), nullable=False))
    op.add_column('court_general_full', sa.Column('start_date', sa.String(length=128), nullable=False))
    op.add_column('court_general_full', sa.Column('end_date', sa.String(length=128), nullable=False))
    op.add_column('court_general_full', sa.Column('review', sa.Integer(), nullable=True))
    op.add_column('court_general_full', sa.Column('judge', sa.String(), nullable=True))
    op.add_column('court_general_full', sa.Column('articles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('court_general_full', sa.Column('papers', sa.String(), nullable=True))
    op.add_column('court_general_full', sa.Column('papers_pretty', sa.String(), nullable=True))
    op.add_column('court_general_full', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'court_general_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('court_general_full', 'person_uuid')
    op.add_column('court_general_preview', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.alter_column('court_general_preview', 'plan',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_general_preview', 'deff',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_general_preview', 'declarant',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_general_preview', 'face',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_general_preview', 'lawyer',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'court_general_preview', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('court_general_preview', 'person_uuid')
    op.add_column('deposits_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deposits_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('deposits_full', 'person_uuid')
    op.add_column('deposits_preview', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deposits_preview', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('deposits_preview', 'person_uuid')
    op.add_column('disqualified_person_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'disqualified_person_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('disqualified_person_full', 'person_uuid')
    op.add_column('disqualified_person_preview', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'disqualified_person_preview', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('disqualified_person_preview', 'person_uuid')
    op.add_column('fssp_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fssp_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fssp_full', 'person_uuid')
    op.add_column('fssp_preview', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fssp_preview', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fssp_preview', 'person_uuid')
    op.add_column('ml_index_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ml_index_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ml_index_full', 'person_uuid')
    op.add_column('part_in_org_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'part_in_org_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('part_in_org_full', 'person_uuid')
    op.add_column('part_in_org_preview', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'part_in_org_preview', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('part_in_org_preview', 'person_uuid')
    op.add_column('tax_arrears_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tax_arrears_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tax_arrears_full', 'person_uuid')
    op.add_column('terror_list_full', sa.Column('irbis_person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'terror_list_full', 'irbis_person', ['irbis_person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('terror_list_full', 'person_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terror_list_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'terror_list_full', type_='foreignkey')
    op.drop_column('terror_list_full', 'irbis_person_id')
    op.add_column('tax_arrears_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tax_arrears_full', type_='foreignkey')
    op.drop_column('tax_arrears_full', 'irbis_person_id')
    op.add_column('part_in_org_preview', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'part_in_org_preview', type_='foreignkey')
    op.drop_column('part_in_org_preview', 'irbis_person_id')
    op.add_column('part_in_org_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'part_in_org_full', type_='foreignkey')
    op.drop_column('part_in_org_full', 'irbis_person_id')
    op.add_column('ml_index_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ml_index_full', type_='foreignkey')
    op.drop_column('ml_index_full', 'irbis_person_id')
    op.add_column('fssp_preview', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fssp_preview', type_='foreignkey')
    op.drop_column('fssp_preview', 'irbis_person_id')
    op.add_column('fssp_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fssp_full', type_='foreignkey')
    op.drop_column('fssp_full', 'irbis_person_id')
    op.add_column('disqualified_person_preview', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'disqualified_person_preview', type_='foreignkey')
    op.drop_column('disqualified_person_preview', 'irbis_person_id')
    op.add_column('disqualified_person_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'disqualified_person_full', type_='foreignkey')
    op.drop_column('disqualified_person_full', 'irbis_person_id')
    op.add_column('deposits_preview', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deposits_preview', type_='foreignkey')
    op.drop_column('deposits_preview', 'irbis_person_id')
    op.add_column('deposits_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deposits_full', type_='foreignkey')
    op.drop_column('deposits_full', 'irbis_person_id')
    op.add_column('court_general_preview', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'court_general_preview', type_='foreignkey')
    op.alter_column('court_general_preview', 'lawyer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_general_preview', 'face',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_general_preview', 'declarant',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_general_preview', 'deff',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_general_preview', 'plan',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('court_general_preview', 'irbis_person_id')
    op.add_column('court_general_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'court_general_full', type_='foreignkey')
    op.drop_column('court_general_full', 'links')
    op.drop_column('court_general_full', 'papers_pretty')
    op.drop_column('court_general_full', 'papers')
    op.drop_column('court_general_full', 'articles')
    op.drop_column('court_general_full', 'judge')
    op.drop_column('court_general_full', 'review')
    op.drop_column('court_general_full', 'end_date')
    op.drop_column('court_general_full', 'start_date')
    op.drop_column('court_general_full', 'process_type')
    op.drop_column('court_general_full', 'court_name')
    op.drop_column('court_general_full', 'region')
    op.drop_column('court_general_full', 'case_number')
    op.drop_column('court_general_full', 'irbis_person_id')
    op.add_column('court_general_category', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'court_general_category', type_='foreignkey')
    op.drop_column('court_general_category', 'irbis_person_id')
    op.add_column('corruption_preview', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'corruption_preview', type_='foreignkey')
    op.drop_column('corruption_preview', 'irbis_person_id')
    op.add_column('corruption_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'corruption_full', type_='foreignkey')
    op.drop_column('corruption_full', 'irbis_person_id')
    op.add_column('bankruptcy_preview', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bankruptcy_preview', type_='foreignkey')
    op.drop_column('bankruptcy_preview', 'irbis_person_id')
    op.add_column('bankruptcy_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bankruptcy_full', type_='foreignkey')
    op.drop_column('bankruptcy_full', 'irbis_person_id')
    op.add_column('arbitr_court_preview', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'arbitr_court_preview', type_='foreignkey')
    op.drop_column('arbitr_court_preview', 'irbis_person_id')
    op.add_column('arbitr_court_full', sa.Column('person_uuid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'arbitr_court_full', type_='foreignkey')
    op.drop_column('arbitr_court_full', 'irbis_person_id')
    op.create_table('court_general_header',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('court_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('process_type', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('review', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('judge', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('articles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('papers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('papers_pretty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_general_full.id'], name='court_general_header_case_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='court_general_header_pkey')
    )
    op.drop_table('irbis_person')
    # ### end Alembic commands ###
