"""добавлена связь ролей с арбитражными судами

Revision ID: 4fee7bd6ecdc
Revises: aabe97d093f6
Create Date: 2025-09-02 19:05:43.184554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fee7bd6ecdc'
down_revision: Union[str, None] = 'aabe97d093f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitr_court_full', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'arbitr_court_full', 'person_role_types', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('arbitr_court_full', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitr_court_full', sa.Column('role', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'arbitr_court_full', type_='foreignkey')
    op.drop_column('arbitr_court_full', 'role_id')
    # ### end Alembic commands ###
