"""связка региона и суда общей юрисдикции

Revision ID: 5b3807a329e8
Revises: 220947b8973f
Create Date: 2025-08-27 10:42:39.432825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3807a329e8'
down_revision: Union[str, None] = '220947b8973f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_general_full', sa.Column('region_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'court_general_full', 'region_subjects', ['region_id'], ['id'], ondelete='CASCADE')
    op.drop_column('court_general_full', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_general_full', sa.Column('region', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'court_general_full', type_='foreignkey')
    op.drop_column('court_general_full', 'region_id')
    # ### end Alembic commands ###
