"""добавлено новое поле в таблицу запросов

Revision ID: 5db64a671475
Revises: 3da7d5f9b623
Create Date: 2025-08-06 11:00:22.026193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db64a671475'
down_revision: Union[str, None] = '3da7d5f9b623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('resource_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries_data', 'resource_type')
    # ### end Alembic commands ###
