"""убран столбец с языком слова

Revision ID: 5fbb8ae78475
Revises: 253d6c42ebf8
Create Date: 2025-05-10 22:25:28.844053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbb8ae78475'
down_revision: Union[str, None] = '253d6c42ebf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'word_language')
    op.drop_constraint('user_balances_user_id_fkey', 'user_balances', type_='foreignkey')
    op.create_foreign_key(None, 'user_balances', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_balances', type_='foreignkey')
    op.create_foreign_key('user_balances_user_id_fkey', 'user_balances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('keywords', sa.Column('word_language', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
