"""поправлены связи

Revision ID: 6fdbe5720ece
Revises: e1f73730b725
Create Date: 2025-05-12 11:32:00.469065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdbe5720ece'
down_revision: Union[str, None] = 'e1f73730b725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_history_user_id_fkey', 'payment_history', type_='foreignkey')
    op.create_foreign_key(None, 'payment_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('queries_balance_query_id_fkey', 'queries_balance', type_='foreignkey')
    op.create_foreign_key(None, 'queries_balance', 'user_queries', ['query_id'], ['query_id'], ondelete='CASCADE')
    op.drop_constraint('telegram_notifications_user_id_fkey', 'telegram_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('text_data_query_id_fkey', 'text_data', type_='foreignkey')
    op.create_foreign_key(None, 'text_data', 'user_queries', ['query_id'], ['query_id'], ondelete='CASCADE')
    op.drop_constraint('user_balances_user_id_fkey', 'user_balances', type_='foreignkey')
    op.create_foreign_key(None, 'user_balances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_queries_user_id_fkey', 'user_queries', type_='foreignkey')
    op.create_foreign_key(None, 'user_queries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_queries', type_='foreignkey')
    op.create_foreign_key('user_queries_user_id_fkey', 'user_queries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_balances', type_='foreignkey')
    op.create_foreign_key('user_balances_user_id_fkey', 'user_balances', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'text_data', type_='foreignkey')
    op.create_foreign_key('text_data_query_id_fkey', 'text_data', 'user_queries', ['query_id'], ['query_id'])
    op.drop_constraint(None, 'telegram_notifications', type_='foreignkey')
    op.create_foreign_key('telegram_notifications_user_id_fkey', 'telegram_notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'queries_balance', type_='foreignkey')
    op.create_foreign_key('queries_balance_query_id_fkey', 'queries_balance', 'user_queries', ['query_id'], ['query_id'])
    op.drop_constraint(None, 'payment_history', type_='foreignkey')
    op.create_foreign_key('payment_history_user_id_fkey', 'payment_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
