"""Добавлен Null к таблицам

Revision ID: 7334917926df
Revises: ffbce1f328c9
Create Date: 2025-09-21 19:23:39.580327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7334917926df'
down_revision: Union[str, None] = 'ffbce1f328c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arbitr_court_full', 'court_name_val',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('arbitr_court_full', 'case_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('arbitr_court_full', 'case_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('arbitr_court_full', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('arbitr_court_full', 'address_val',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('arbitr_court_oponents', 'arbitration_court_full_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bankruptcy_full', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'second_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'birth_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'born_place',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('bankruptcy_full', 'inn',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'ogrn',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'snils',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'category_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'location',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('bankruptcy_full', 'region_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bankruptcy_full', 'information',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('bankruptcy_full', 'link',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('corruption_full', 'full_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('corruption_full', 'organization',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('corruption_full', 'position',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('corruption_full', 'normative_act',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('corruption_full', 'application_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('corruption_full', 'publish_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('corruption_full', 'excluded_reason',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('court_general_faces', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('court_general_faces', 'role_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('court_general_faces', 'face',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('court_general_full', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('court_general_full', 'court_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('court_general_full', 'start_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('court_general_full', 'end_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('disqualified_person_full', 'birth_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('disqualified_person_full', 'fio',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('disqualified_person_full', 'article',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('disqualified_person_full', 'start_date_disq',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('disqualified_person_full', 'end_date_disq',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('disqualified_person_full', 'bornplace',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('disqualified_person_full', 'fio_judge',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('disqualified_person_full', 'office_judge',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('disqualified_person_full', 'legal_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('disqualified_person_full', 'office',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('disqualified_person_full', 'department',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('fssp_full', 'ip',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('fssp_full', 'fio',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('fssp_full', 'rosp',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('fssp_full', 'type_ip',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('fssp_full', 'summ',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('fssp_full', 'rekv',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('fssp_full', 'end_cause',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('fssp_full', 'pristav',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('ml_index_full', 'scoring',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('ml_index_full', 'errors',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ml_index_full', 'progress',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('ml_index_full', 'popularity_full',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('ml_index_full', 'popularity_short',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('part_in_org_individual', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('part_in_org_individual', 'inn',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('part_in_org_organization', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('part_in_org_organization', 'inn',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('part_in_org_roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('part_in_org_roles', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pledge_items', 'pledge_num_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('pledge_items', 'pledge_num',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('pledge_items', 'pledge_type',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('pledge_parties', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pledge_parties', 'type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('pledge_parties', 'subtype',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('tax_arrears_fields', 'type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('tax_arrears_fields', 'field_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('tax_arrears_fields', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tax_arrears_full', 'provider',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('tax_arrears_full', 'money_name',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('tax_arrears_full', 'money_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('terror_list_full', 'fio',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('terror_list_full', 'birth_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('terror_list_full', 'birth_place',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terror_list_full', 'birth_place',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('terror_list_full', 'birth_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('terror_list_full', 'fio',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('tax_arrears_full', 'money_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('tax_arrears_full', 'money_name',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('tax_arrears_full', 'provider',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('tax_arrears_fields', 'value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tax_arrears_fields', 'field_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('tax_arrears_fields', 'type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('pledge_parties', 'subtype',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('pledge_parties', 'type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('pledge_parties', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pledge_items', 'pledge_type',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('pledge_items', 'pledge_num',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('pledge_items', 'pledge_num_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('part_in_org_roles', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('part_in_org_roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('part_in_org_organization', 'inn',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('part_in_org_organization', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('part_in_org_individual', 'inn',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('part_in_org_individual', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ml_index_full', 'popularity_short',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('ml_index_full', 'popularity_full',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('ml_index_full', 'progress',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('ml_index_full', 'errors',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ml_index_full', 'scoring',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('fssp_full', 'pristav',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('fssp_full', 'end_cause',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('fssp_full', 'rekv',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('fssp_full', 'summ',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('fssp_full', 'type_ip',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('fssp_full', 'rosp',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('fssp_full', 'fio',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('fssp_full', 'ip',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'department',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'office',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'legal_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'office_judge',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'fio_judge',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'bornplace',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'end_date_disq',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('disqualified_person_full', 'start_date_disq',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('disqualified_person_full', 'article',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'fio',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('disqualified_person_full', 'birth_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('court_general_full', 'end_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('court_general_full', 'start_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('court_general_full', 'court_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('court_general_full', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('court_general_faces', 'face',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('court_general_faces', 'role_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('court_general_faces', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('corruption_full', 'excluded_reason',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('corruption_full', 'publish_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('corruption_full', 'application_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('corruption_full', 'normative_act',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('corruption_full', 'position',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('corruption_full', 'organization',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('corruption_full', 'full_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('bankruptcy_full', 'link',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('bankruptcy_full', 'information',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('bankruptcy_full', 'region_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bankruptcy_full', 'location',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('bankruptcy_full', 'category_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bankruptcy_full', 'snils',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bankruptcy_full', 'ogrn',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bankruptcy_full', 'inn',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bankruptcy_full', 'born_place',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('bankruptcy_full', 'birth_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bankruptcy_full', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bankruptcy_full', 'second_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bankruptcy_full', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('arbitr_court_oponents', 'arbitration_court_full_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('arbitr_court_full', 'address_val',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('arbitr_court_full', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('arbitr_court_full', 'case_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('arbitr_court_full', 'case_date',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('arbitr_court_full', 'court_name_val',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
