"""убраны лишние поля

Revision ID: 8b665204b0c5
Revises: 4fee7bd6ecdc
Create Date: 2025-09-03 12:23:03.424901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b665204b0c5'
down_revision: Union[str, None] = '4fee7bd6ecdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corruption_full', 'key')
    op.drop_column('disqualified_person_full', 'response_id')
    op.drop_column('disqualified_person_full', 'reestr_key')
    op.drop_column('fssp_full', 'response_id')
    op.add_column('tax_arrears_fields', sa.Column('tax_arrear_id', sa.Integer(), nullable=False))
    op.drop_constraint('tax_arrears_fields_arrear_id_fkey', 'tax_arrears_fields', type_='foreignkey')
    op.create_foreign_key(None, 'tax_arrears_fields', 'tax_arrears_full', ['tax_arrear_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tax_arrears_fields', 'field_id')
    op.drop_column('tax_arrears_fields', 'field_type')
    op.drop_column('tax_arrears_fields', 'arrear_id')
    op.drop_column('tax_arrears_full', 'money_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_arrears_full', sa.Column('money_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tax_arrears_fields', sa.Column('arrear_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tax_arrears_fields', sa.Column('field_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('tax_arrears_fields', sa.Column('field_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tax_arrears_fields', type_='foreignkey')
    op.create_foreign_key('tax_arrears_fields_arrear_id_fkey', 'tax_arrears_fields', 'tax_arrears_full', ['arrear_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tax_arrears_fields', 'tax_arrear_id')
    op.add_column('fssp_full', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('disqualified_person_full', sa.Column('reestr_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('disqualified_person_full', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('corruption_full', sa.Column('key', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
