"""изменена таблица ключевых слов

Revision ID: a0f7b833fef7
Revises: 5db64a671475
Create Date: 2025-08-10 11:14:02.154128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f7b833fef7'
down_revision: Union[str, None] = '5db64a671475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('keywords', sa.Column('keyword_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'keywords', 'keyword_type', ['keyword_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('keywords', 'word_type')
    op.add_column('queries_data', sa.Column('keyword_type_id', sa.Text(), nullable=True))
    op.drop_column('queries_data', 'keyword_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('keyword_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('queries_data', 'keyword_type_id')
    op.add_column('keywords', sa.Column('word_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'keywords', type_='foreignkey')
    op.drop_column('keywords', 'keyword_type_id')
    op.drop_table('keyword_type')
    # ### end Alembic commands ###
