"""Update TextData

Revision ID: a90b9cbb452c
Revises: 5fbb8ae78475
Create Date: 2025-05-11 16:27:16.888978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90b9cbb452c'
down_revision: Union[str, None] = '5fbb8ae78475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_data', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.drop_column('text_data', 'query_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_data', sa.Column('query_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('text_data', 'file_path')
    # ### end Alembic commands ###
