"""обновлена бд для хранения данных запроса

Revision ID: a96799621454
Revises: b04baecebe53
Create Date: 2025-08-11 13:33:08.951024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96799621454'
down_revision: Union[str, None] = 'b04baecebe53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_translation_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['user_queries.query_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('queries_data', sa.Column('keyword', sa.String(length=30), nullable=True))
    op.alter_column('queries_data', 'resource_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_column('queries_data', 'keyword_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('keyword_type_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('queries_data', 'resource_type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('queries_data', 'keyword')
    op.drop_table('query_translation_languages')
    # ### end Alembic commands ###
