"""добавлено поле для связи с типами арбитражных дел

Revision ID: aabe97d093f6
Revises: 02c8382f08c7
Create Date: 2025-09-01 20:00:44.461432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabe97d093f6'
down_revision: Union[str, None] = '02c8382f08c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitr_court_case_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('arbitr_court_full', sa.Column('case_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'arbitr_court_full', 'arbitr_court_case_types', ['case_type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('arbitr_court_full', 'case_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitr_court_full', sa.Column('case_type', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'arbitr_court_full', type_='foreignkey')
    op.drop_column('arbitr_court_full', 'case_type_id')
    op.drop_table('arbitr_court_case_types')
    # ### end Alembic commands ###
