"""добавлено последнее посещение

Revision ID: b0034578969e
Revises: 6fdbe5720ece
Create Date: 2025-05-21 21:41:56.258780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0034578969e'
down_revision: Union[str, None] = '6fdbe5720ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_history_user_id_fkey', 'payment_history', type_='foreignkey')
    op.create_foreign_key(None, 'payment_history', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('last_visited', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_visited')
    op.drop_constraint(None, 'payment_history', type_='foreignkey')
    op.create_foreign_key('payment_history_user_id_fkey', 'payment_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
