"""добавлена таблица для категорий поиска запроса

Revision ID: b04baecebe53
Revises: 3a63e06ad400
Create Date: 2025-08-10 12:59:03.466495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04baecebe53'
down_revision: Union[str, None] = '3a63e06ad400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_search_category_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_searcg_category_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_search_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('search_category_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['user_queries.query_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_category_type_id'], ['query_search_category_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_search_category')
    op.drop_table('query_search_category_type')
    # ### end Alembic commands ###
