"""добавил столбец под сумму остатка

Revision ID: ba37df0d05e9
Revises: c9e1e05c2345
Create Date: 2025-05-26 18:45:41.276163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba37df0d05e9'
down_revision: Union[str, None] = 'c9e1e05c2345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services_balance', sa.Column('balance_threshold', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services_balance', 'balance_threshold')
    # ### end Alembic commands ###
