"""поправлена таблица с организациями

Revision ID: c6779c487337
Revises: 8b665204b0c5
Create Date: 2025-09-03 14:06:47.976477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6779c487337'
down_revision: Union[str, None] = '8b665204b0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_in_org_organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('okved', sa.String(length=200), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part_in_org_full.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['region_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('part_in_org_org')
    op.drop_index('idx_court_general_irbis_person', table_name='court_general_full')
    op.drop_index('idx_court_general_match_type', table_name='court_general_full')
    op.drop_index('idx_court_general_process_type', table_name='court_general_full')
    op.drop_index('idx_court_general_region', table_name='court_general_full')
    op.drop_column('part_in_org_full', 'part_type')
    op.drop_column('part_in_org_full', 'filter_type')
    op.drop_column('part_in_org_full', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_in_org_full', sa.Column('count', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('part_in_org_full', sa.Column('filter_type', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('part_in_org_full', sa.Column('part_type', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_index('idx_court_general_region', 'court_general_full', ['region_id'], unique=False)
    op.create_index('idx_court_general_process_type', 'court_general_full', ['process_type_id'], unique=False)
    op.create_index('idx_court_general_match_type', 'court_general_full', ['match_type_id'], unique=False)
    op.create_index('idx_court_general_irbis_person', 'court_general_full', ['irbis_person_id'], unique=False)
    op.create_table('part_in_org_org',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inn', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ogrn', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('adress', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('okved', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part_in_org_full.id'], name='part_in_org_org_part_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='part_in_org_org_pkey')
    )
    op.drop_table('part_in_org_organization')
    # ### end Alembic commands ###
