"""добавлена таблица связка языков и стран

Revision ID: c9e1e05c2345
Revises: 8d4a28678679
Create Date: 2025-05-23 14:50:17.649439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e1e05c2345'
down_revision: Union[str, None] = '8d4a28678679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('countries_language_id_fkey', 'countries', type_='foreignkey')
    op.drop_column('countries', 'language_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('countries_language_id_fkey', 'countries', 'languages', ['language_id'], ['id'])
    op.drop_table('country_languages')
    # ### end Alembic commands ###
