"""добавлен тип поиска по совпадению

Revision ID: ce13f5a7e7ba
Revises: de4a1b43f94e
Create Date: 2025-08-25 17:29:59.049517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce13f5a7e7ba'
down_revision: Union[str, None] = 'de4a1b43f94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_general_full', sa.Column('match_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'court_general_full', 'match_types', ['match_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'court_general_full', type_='foreignkey')
    op.drop_column('court_general_full', 'match_type_id')
    # ### end Alembic commands ###
