"""add unique telegram

Revision ID: cf565268771a
Revises: 9e54a34f95f7
Create Date: 2025-05-05 15:34:24.988152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf565268771a'
down_revision: Union[str, None] = '9e54a34f95f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'telegram_notifications', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_notifications', type_='unique')
    # ### end Alembic commands ###
