"""Update columns

Revision ID: de5e72054370
Revises: 4aaf5e9316bd
Create Date: 2025-05-02 18:25:34.788136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5e72054370'
down_revision: Union[str, None] = '4aaf5e9316bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_history', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('balance_history', 'transaction_id')
    op.add_column('queries_balance', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries_balance', 'id')
    op.add_column('balance_history', sa.Column('transaction_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('balance_history', 'id')
    # ### end Alembic commands ###
