"""добавлено поле для хранение состояние полного имени

Revision ID: e1c8f66cf49a
Revises: ffd0ecda1f87
Create Date: 2025-08-21 17:39:54.035541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c8f66cf49a'
down_revision: Union[str, None] = 'ffd0ecda1f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('is_fullname', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries_data', 'is_fullname')
    # ### end Alembic commands ###
