"""добавлена таблица языков

Revision ID: e1f73730b725
Revises: a90b9cbb452c
Create Date: 2025-05-12 11:22:04.549012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f73730b725'
down_revision: Union[str, None] = 'a90b9cbb452c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('english_name', sa.String(length=100), nullable=False),
    sa.Column('russian_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_constraint('events_query_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'user_queries', ['query_id'], ['query_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_query_id_fkey', 'events', 'user_queries', ['query_id'], ['query_id'], ondelete='CASCADE')
    op.drop_table('languages')
    # ### end Alembic commands ###
