"""возвращен id типа ключевого слова

Revision ID: e6c1f3dc330a
Revises: a96799621454
Create Date: 2025-08-11 13:35:24.098478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c1f3dc330a'
down_revision: Union[str, None] = 'a96799621454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('keyword_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'queries_data', 'keyword_type', ['keyword_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries_data', type_='foreignkey')
    op.drop_column('queries_data', 'keyword_type_id')
    # ### end Alembic commands ###
