"""добавлена колонка для русского перевода

Revision ID: f1cc96a92a71
Revises: e6c1f3dc330a
Create Date: 2025-08-11 13:52:01.238709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cc96a92a71'
down_revision: Union[str, None] = 'e6c1f3dc330a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_search_category_type', sa.Column('query_searcg_category_type_ru', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_search_category_type', 'query_searcg_category_type_ru')
    # ### end Alembic commands ###
