"""поправлена таблица банкротств

Revision ID: ffbce1f328c9
Revises: 1014f0ecd02c
Create Date: 2025-09-03 17:28:47.289477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbce1f328c9'
down_revision: Union[str, None] = '1014f0ecd02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankruptcy_full', sa.Column('search_type', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bankruptcy_full', 'search_type')
    # ### end Alembic commands ###
