"""добавлена реализация хранения ключевых слов в запросе

Revision ID: ffd0ecda1f87
Revises: f1cc96a92a71
Create Date: 2025-08-20 17:09:32.717252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd0ecda1f87'
down_revision: Union[str, None] = 'f1cc96a92a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_data_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_data_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('original_keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_data_id'], ['queries_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('queries_data_keyword_type_id_fkey', 'queries_data', type_='foreignkey')
    op.drop_column('queries_data', 'keyword_type_id')
    op.drop_column('queries_data', 'keyword')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries_data', sa.Column('keyword', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('queries_data', sa.Column('keyword_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('queries_data_keyword_type_id_fkey', 'queries_data', 'keyword_type', ['keyword_type_id'], ['id'], ondelete='SET NULL')
    op.drop_table('query_data_keywords')
    # ### end Alembic commands ###
